### PR TITLE
DX-743: Replace all the /pages with next.js dynamic pages and routes.

### PR DESCRIPTION
**Pull request by AGS1130**
DX-743

@kevinold @robertguss I'm keeping the Vue files at the moment in case we need to reference styles, logic, etc. Let me know if y'all feel that it can be safely removed.

### CODE REVIEW

**Comment by kevinold** [comment]
@AGS1130 As we discussed, let's keep the Vue files as is and remove them once we're certain all have been recreated as React components.

**Comment by AGS1130** [comment]
This will also cover DX-744, as it needed the React components from the `_cypress-nextjs-docs` .project

**Comment by robertguss** [comment]
@AGS1130 Hey Greg, the point of this ticket was to replace all of the dynamic nuxt pages in the `/pages` directory with next.js dynamic pages. No worries though. We can keep this PR as is and merge it, but let's re-create all of those dynamic pages and get those all working for the next piece of work. 

So, in the next PR, Next should be generating all of the guides, api's, examples, for each markdown file in the `/content` directory.

**Review by robertguss — APPROVED** [review]

**Comment by kevinold** [comment]
@AGS1130 Please update this PR to limit the scope of what is committed, as @robertguss detailed in the Linear issue(s) and in his comment earlier.

**Review by robertguss — APPROVED** [review]

**Review by kevinold — APPROVED** [review]

**Pull request merged**
