### PR TITLE
Translate typescript-support.md into Chinese

### PR DESCRIPTION
**Pull request by hiwanz**
Update the doc with new one by copying the contents from English version and finish the translation

### CODE REVIEW

**Comment by hiwanz** [comment]
Running Cypress tests timeout.Maybe someone could start it again.

**Comment by GreatAuk** [comment]
Chinese translation has been deleted

**Comment by hiwanz** [comment]
> 😭， Chinese translation has been deleted ？

Seems so.

**Comment by GreatAuk** [comment]
> > 😭， Chinese translation has been deleted ？
> 
> Seems so.

How to read history version documents?

**Comment by hiwanz** [comment]
> > > 😭， Chinese translation has been deleted ？
> > 
> > 
> > Seems so.
> 
> How to read history version documents?

the last translation i commit is https://github.com/cypress-io/cypress-documentation/tree/eb04b01180b8823976d4e282b060df99ab8b5a9e/source/zh-cn/guides , you can follow this link to get what you need, but it may be outdated

**Pull request merged**
