### PR TITLE
docs: fix link format

### PR DESCRIPTION
**Pull request by Manuel-Suarez-Abascal**
**Fixes:** [issue-4936](https://github.com/cypress-io/cypress-documentation/issues/4936)

**Before changes:**

Screenshot 2022-12-17 at 7 16 40 PM

**After changes:**

https://user-images.githubusercontent.com/32891808/208301795-02c1e0ef-5690-4280-97be-93e7431bfac4.mov

### CODE REVIEW

**Comment by jaffrepaul** [comment]
Thanks @Manuel-Suarez-Abascal! Please sign the Contributor License Agreement above and we can merge this change.

**Comment by Manuel-Suarez-Abascal** [comment]
> Thanks @Manuel-Suarez-Abascal! Please sign the Contributor License Agreement above and we can merge this change.

It's done ❤️

**Comment by jaffrepaul** [comment]
@Manuel-Suarez-Abascal can you get a look again at the CLA? Looks like there may be an issue:
Screen Shot 2022-12-20 at 9 55 47 AM

**Comment by Manuel-Suarez-Abascal** [comment]
> @Manuel-Suarez-Abascal can you get a look again at the CLA? Looks like there may be an issue: Screen Shot 2022-12-20 at 9 55 47 AM

I have the same issue when contributing to the Cypress repo recently. I am not sure why, but I did signed the agreement 🤷🏻

**Comment by jaffrepaul** [comment]
@Manuel-Suarez-Abascal Thanks for signing the CLA, unfortunately the author of the commits does not match the email address on your GitHub account. Our CLA bot gets confused when they don’t match. Here are some solutions to fixing when commits are linked to the wrong user: https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/

**Comment by Manuel-Suarez-Abascal** [comment]
@jaffrepaul close this PR in favor: https://github.com/cypress-io/cypress-documentation/pull/4946 in order to fix the CLA issue. It seems to be working fine now.

**Pull request closed without merging**
