### PR TITLE
Update error-messages.md (Expected to find element...)

### PR DESCRIPTION
**Pull request by lots0logs**
Added an error case that could help others avoid days spinning their wheels trying to find the problem like I did.

### Translations updated

Changes made to documentation were also copied over to other languages (**copying English text is ok**).

- [x] Japanese docs in [`/source/ja`](/source/ja).
- [x] Chinese docs in [`/source/zh-cn`](/source/zh-cn).
- [ ] Not applicable (this is not a change to an `en` doc content).

### CODE REVIEW

**Comment by jennifer-shehane** [comment]
@lots0logs Sorry for the delay. Our CLA assistant was having some issues with linking. Could you please sign our CLA?

**Comment by lots0logs** [comment]
Hmm..something is wrong with it. Its not working now. It let me sign at the time I created the PR and it showed it was signed.

**Comment by lots0logs** [comment]
@jennifer-shehane @flotwig It looks like the entry I added got moved to the Page Load Errors section during merge. Was that intentional or an unintended result of merge conflict resolution? Seems like it should go under the Commands section where I had it originally :thinking:

**Comment by flotwig** [comment]
Good eye @lots0logs, I'll fix that up

**Pull request merged**
