### PR TITLE
add edge to the list of browsers

### PR DESCRIPTION
**Pull request by bahmutov**
Mention new Microsoft Edge among browsers for https://github.com/cypress-io/cypress/pull/6181

### CODE REVIEW

**Comment by jennifer-shehane** [comment]
Changing base to 4.0 branch which is targeted release.

**Comment by bahmutov** [comment]
Exactly agree with you @jennifer-shehane - that's why Edge should be its own minor version - because this just adds to the complexity, rather than doing it step by step and observing.

**Comment by bahmutov** [comment]
ok, so `isBrowser` and `isBrowserType` is a new thing from Firefox branch, not part of this edge work or `4.0-release` branch - I don't see it in https://github.com/cypress-io/cypress/pull/4226/files that's why I cannot add it to Edge work

**Comment by jennifer-shehane** [comment]
Ok, we'll work it out when we get the repos merged in together towards release.

**Comment by jennifer-shehane** [comment]
I'm merging these 3 separate PRs together to get a working 4.0 doc branch.

**Pull request merged**
