### PR TITLE
Reference recommendation not to use after(Each)

### PR DESCRIPTION
**Pull request by DanAtShenTech**
Link to the recommendation not to use the anti-pattern of cleaning up state with after()/afterEach()

### CODE REVIEW

**Comment by DanAtShenTech** [comment]
I couldn't determine how to use the 'url' helper in order to make the proper link.  If you agree with this addition to the docs, will you update the PR with the necessary change to 'url'?

**Comment by brian-mann** [comment]
The URL helper references the unique name of the document - in this case it would be "best-practices"

And then if you use a hash it will go out and validate that that hash could be found. So the url helper should be...

```
{% url 'text' nameOfDoc %}
{% url 'text' nameOfDoc#hash %}
{% url 'the text you want here' best-practices#Using-after-or-afterEach-hooks %}
```

**Comment by DanAtShenTech** [comment]
Thanks Brian.

**Comment by jennifer-shehane** [comment]
Sorry, yup, I did not write the link right. Got caught up in fixing the `docs` url and the markdown link. Brian's change is the fix. ^

**Pull request merged**
