### PR TITLE
Add cypress-mailosaur plugin: Mailosaur email and SMS testing commands

### PR DESCRIPTION
**Pull request by hippyhorse**
Added reference to the officially-supported Mailosaur commands for Cypress:
https://github.com/mailosaur/cypress-mailosaur

### CODE REVIEW

**Comment by hippyhorse** [comment]
@jennifer-shehane @bencodezen Updated to resolve conflicts. Is this one OK to merge?

**Comment by hippyhorse** [comment]
The docs tests are failing and I cannot immediately see why, so any assistance would be great.

**Comment by hippyhorse** [comment]
Just pinging on this, are we now OK to merge this as all passing?

**Comment by jennifer-shehane** [comment]
Sorry for the delay!

**Comment by andosaur** [comment]
@jennifer-shehane thanks!

**Pull request merged**
