### PR TITLE
Updates for Chrome Beta support

### PR DESCRIPTION
**Pull request by chrisbreiding**
For https://github.com/cypress-io/cypress/pull/16518

### CODE REVIEW

**Comment by jennifer-shehane** [comment]
Probably would be nice to update the image in the browsers section: Screen Shot 2021-05-14 at 11 05 05 AM

**Comment by jennifer-shehane** [comment]
Updated the base branch to be against 7.4.0-release, I don't see any reason this won't go out then.

**Comment by chrisbreiding** [comment]
@jennifer-shehane I update the browser dropdown image. Would you mind reviewing again?

**Review by jennifer-shehane — APPROVED** [review]
Looks good

**Pull request merged**
