### PR TITLE
Added cypress-hmr-restarter to plugins

### PR DESCRIPTION
**Pull request by Svish**
As requested by @jennifer-shehane in https://github.com/cypress-io/cypress/issues/456#issuecomment-610847058

### CODE REVIEW

**Comment by jennifer-shehane** [comment]
Thanks for the contribution! Could you please sign our CLA?

**Comment by Svish** [comment]
Done. Sorry, misread the message and thought I already had.

**Review by bencodezen — CHANGES_REQUESTED** [review]
👋 Hey @Svish! Thank you for your contribution!

We're reviewing your plugin. Here are some guidelines that we use as we review our plugin:

- [] 🚀 Works with the latest major version of Cypress
- [] 🛠 Plugin purpose is clearly documented (in a README or docs website)
- [] 📄 Well-written documentation - A great example ([link](https://github.com/Fredx87/cypress-keycloak-commands#cypress-keycloak-commands))
- [] 🧪 Tested using Cypress - tests using Cypress can act as both example usage _and_ test coverage
- [] 👷‍♀️ CI pipeline that's passing (CircleCI and [Github Actions](https://github.com/cypress-io/cypress-tutorial-build-todo/blob/master/.github/workflows) are both free for Open Source)

Based on reviewing the plugin, it looks like your plugin could use some tests as well as more documentation on how to use your plugin. Once you have these parts, I'd be happy to take a second look. Let me know if you have any questions!

**Comment by Svish** [comment]
@bencodezen I agree, in theory, but...

**Tests:** This is a plugin for developers, and to test it you'd need a full on app using hmr running, a full on cypress test suite running _in interactive mode_, simulate a developer editing files, and verify that the cypress tests restart. No clue how to even begin automating testing that locally, yet alone in a CI setting. Way too much work, and not something I want to spend hours and hours on doing. The plugin is very simple, and is in use in our project, so I already know it works.

**Docs:** What more documentation do you need? Your example of "well-written documentation" is great, but this plugin is so simple there's literally nothing more to document. You install it, you add a single line to your support file (as already documented), and that's it. It does what it does, nothing more, nothing less.

You were the ones asking me to add this plugin to your list, which I have. But I'm not going to spend weeks on figuring out how to write automated CI tests for this, if it's even possible to do. I don't mind improving the documentation, but then you need to tell me what "more" you need to see, as I really can't think of anything. The first line says what it does, the next section shows how to install it, and the last section explains how it works. What else do you need to know?

**Comment by Svish** [comment]
(sorry for the rant, I do mean it, but possibly came out way more negative/difficult than it maybe could've 🤔)

**Comment by bencodezen** [comment]
My apologies @Svish. I missed some of the original context around this PR and have a better understanding around it now. 

As far as a suggestion of improvement, I think it would help to do a GIF / screen capture video of your plugin working in an app to help show it in action; but otherwise, I think we're good to go then.

Thanks for taking the time to create the plugin and PR!

**Review by bencodezen — APPROVED** [review]

**Pull request merged**
