### PR TITLE
Added cypress-terminal-report to plugins list.

### PR DESCRIPTION
**Pull request by archfz**
This change is only to add a plugin to the documentation page for pretty and informative logs on terminal. See https://github.com/archfz/cypress-terminal-report

### CODE REVIEW

**Comment by bahmutov** [comment]
super nice

**Comment by jennifer-shehane** [comment]
@archfz We do an initial smoke test of all plugins requested to be added to our docs. I wasn't able to see any extra output from your plugin and opened an issue here: https://github.com/archfz/cypress-terminal-report/issues/2

**Comment by archfz** [comment]
There is a serious issue with the current version that just got a fix here archfz/cypress-terminal-report#1 It is making tests fail that rely on XMLHTTPREQUEST API for cy.route. I will soon create a release with the fix, we should wait that before this gets merged.

**Comment by jennifer-shehane** [comment]
@archfz I see the PR has been merged, has there been a new release of the fix on the plugin?

**Comment by archfz** [comment]
I am waiting for an additional fix and feature to be merged https://github.com/archfz/cypress-terminal-report/pull/4#issuecomment-587337673 . I will write a comment here when new release is done.

**Comment by archfz** [comment]
The MR was merged. Tests are passing. I have release 1.0.0. We can proceed with this.

**Pull request merged**
