### PR TITLE
Update to add a visual testing plugin

### PR DESCRIPTION
**Pull request by Mikuu**
Add another plugin micoocypress for doing visual regression testing with Micoo

### CODE REVIEW

**Comment by jennifer-shehane** [comment]
@Mikuu Thanks for submitting the plugin! Please check to see if it fulfills these requirements:

- [ ] 🚀 Works with the latest major version of Cypress
- [ ] 🛠 Plugin purpose is clearly documented (in a README or docs website)
- [ ] 📝 Well-written documentation - A great example ([link](https://github.com/Fredx87/cypress-keycloak-commands#cypress-keycloak-commands))
- [ ] 🔬 Tested using Cypress - tests using Cypress can act as both example usage _and_ test coverage
- [ ] 👷‍♀️ CI pipeline that's passing (CircleCI and [Github Actions](https://github.com/cypress-io/cypress-tutorial-build-todo/blob/master/.github/workflows) are both free for Open Source)

If you have reason to believe your plugin does not need to meet certain requirements, please feel free to provide justification.

**Comment by Mikuu** [comment]
@jennifer-shehane yes, I think all of those requirements are matched for this plugin.

**Review by amirrustam — CHANGES_REQUESTED** [review]
@Mikuu the repo of this plugin does not have tests, which is a standard that we require now for plugin submissions. Please refer to @jennifer-shehane's comment for a list of the minimum viable standards we require. Thank you.

**Review by amirrustam — APPROVED** [review]

**Review by amirrustam — CHANGES_REQUESTED** [review]
@Mikuu the repo of this plugin does not have tests, which is a standard that we require now for plugin submissions. Please refer to @jennifer-shehane's comment for a list of the minimum viable standards we require. Thank you.

**Comment by amirrustam** [comment]
@Mikuu closing for now, but feel free to reopen the PR once the plugin can meet the requirements listed here: https://github.com/cypress-io/cypress-documentation/pull/3654#issuecomment-792783408

**Pull request closed without merging**
