### PR TITLE
Convert browser gifs to mp4s

### LINKED ISSUE #1040: Some images getting 403s
From https://docs.cypress.io/guides/guides/launching-browsers.html#Browser-Icon: 
screen shot 2018-10-11 at 10 38 12 am

### PR DESCRIPTION
**Pull request by lilaconlee**
- Fixes #1040

### CODE REVIEW

**Comment by lilaconlee** [comment]
Quality is a bit low, would be great to confirm if that's expected.

screen shot 2018-10-11 at 11 15 47 am

**Comment by jennifer-shehane** [comment]
Did you use the conversion script for this? https://github.com/cypress-io/cypress-documentation/blob/develop/cy_scripts/snippet-creator/convert.js#L6

@Bkucera I actually can't track down where this is documented now.

**Comment by brian-mann** [comment]
I don't think he wrote any docs on this but the CLI has some args and info here: https://github.com/cypress-io/cypress-documentation/blob/develop/cy_scripts/snippet-creator/cli.js

This needs to be added to the readme for sure. I thought all you do is add them to a folder and run the script and it'll auto convert them and you don't even need to pass any arguments, etc.

Can't quite remember but we need it all documented.

**Comment by lilaconlee** [comment]
The mp4s already existed, but they weren't being used.

**Comment by Bkucera** [comment]
Looks like i just missed changing these references from `.gif` to `.mp4` after the conversion :sweat_smile:

**Comment by Bkucera** [comment]
to address @brian-mann , yes I should better document the usage.
Basically you call the script with a path to a `.gif` or `mp4`, and it will place it in snippets alongside a generated thumbnail

**Pull request merged**
