### PR TITLE
Update intercept.mdx

### PR DESCRIPTION
**Pull request by RobinsonRojas**
Fix url variable cy.intercept

### CODE REVIEW

**Comment by jaffrepaul** [comment]
@RobinsonRojas the original example should still work and using the options object as you propose should also do the trick as well, but with a full HTTP request URL. Do you have a reproducible example of the original API not working?

**Comment by RobinsonRojas** [comment]
@jaffrepaul yes this is 

```js
/// <reference types="cypress" />

context('Waiting', () => {
	beforeEach(() => {
		cy.visit('https://example.cypress.io/commands/waiting')
	})

	it('cy.wait() - wait for a specific route', () => {
		// Listen to GET to comments/1

		// CypressError
		cy.intercept('https://jsonplaceholder.cypress.io/comments/1', { times: 1 }).as('getComment') 

		// No CypressError
		// cy.intercept({ url:'https://jsonplaceholder.cypress.io/comments/1',  times: 1 }).as('getComment') 

		cy.get('.network-btn').click()

		// wait for GET comments/1
		cy.wait('@getComment')
			.its('response.statusCode')
			.should('be.oneOf', [200, 304])
	})
})
```
CypressError:
image

No CypressError:
image

**Review by jennifer-shehane — APPROVED** [review]

**Comment by jennifer-shehane** [comment]
@RobinsonRojas Can you run lint on the PR?

**Comment by RobinsonRojas** [comment]
@jennifer-shehane Yes but I didn't find the format error.

**Review by mschile — APPROVED** [review]

**Pull request merged**
