### PR TITLE
Add Cypress courses page

### LINKED ISSUE #1765: Add a page with online training in Cypress
There are several video training tutorials out there, and we should collect them on a single page

- our own tutorial by Andrew
- Andrew's Egghead course
- new Brett's Egghead course
- Udemy course
- testing JavaScript by Kent C Dodd's

### PR DESCRIPTION
**Pull request by bahmutov**
- closes #1765 
- [x] needs styling, which I cannot do

Screen Shot 2019-06-12 at 3 42 34 PM

### CODE REVIEW

**Comment by bahmutov** [comment]
@jennifer-shehane I just added a page and YML file with existing courses, could you make it look slightly less weird, please? People love finding training resources

**Comment by mguery** [comment]
End to End automation testing with Cypress by Karthik KK
https://www.udemy.com/e2e-cypress/

**Comment by bahmutov** [comment]
Ohh so there are two udemy courses, thank you, will add this one

**Comment by jennifer-shehane** [comment]
Tests win again 😈 	Although the title of the test is not helpful - it's failing because it didn't find a corresponding Japanese document for Courses. 

```
  1) Sidebar Titles and links displays titles and links in sidebar:
     AssertionError: expected 'Courses' to equal undefined
```

I'll see if I can update the tests to be more helpful in it's title.

**Pull request merged**
