### PR TITLE
split media into large and small, add small blog links

### LINKED ISSUE #827: Add links to the blogs to https://docs.cypress.io/examples/media/blogs-media.html
In addition to specific blog posts, we should add links to entire blogs

- https://www.cypress.io/blog/
- https://glebbahmutov.com/blog/tags/cypress/

### PR DESCRIPTION
**Pull request by bahmutov**
- close #827 
- move all data links (like blogs.yml) to "large" and add template for "small" links without any thumbnails, just an unordered list of items
- add links to Cypress blog and my blog

screen shot 2018-08-21 at 8 45 46 am

### CODE REVIEW

**Comment by bahmutov** [comment]
the large media thumbnails seem way too heavy, and also we need to distinguish collections of things (like our video channel, or our blog) from the rest of the individual posts. I would maybe add a text after the link to the "small" items though

**Comment by jennifer-shehane** [comment]
Oh I see, those are collections.

**Comment by bahmutov** [comment]
What do you think about this @richdouglasevans ? It is weird to NOT have links to Cypress blog or to my posts about Cypress in "Blogs" section of the documentation, right

**Comment by richdouglasevans** [comment]
Yes. Having the links to the official Cypress blog and your own is great: it makes them _discoverable_ 👍

**Pull request merged**
