### PR TITLE
Update list with new course

### PR DESCRIPTION
**Pull request by wlsf82**
I already have other courses listed here, and now that my advanced Cypress course is live, I'm adding it here too.

### CODE REVIEW

**Comment by wlsf82** [comment]
Hi, @bahmutov, would you mind looking into it, please?

**Review by bahmutov — APPROVED** [review]
nice

**Comment by wlsf82** [comment]
@bahmutov, I can't see my new course on https://docs.cypress.io/examples/media/courses-media.html.
How long does it take to get there?

**Comment by wlsf82** [comment]
Now it's there, thanks!

**Pull request merged**
