### PR TITLE
Dashboard Analytics Beta Docs

### PR DESCRIPTION
**Pull request by kevinold**
Initial Dashboard Analytics Documentation for Beta features.

Related: https://github.com/cypress-io/cypress-dx/issues/35

### CODE REVIEW

**Comment by jennifer-shehane** [comment]
Hey just to clarify - can this be released now as is - or is this waiting on some other work, because as soon as this is merged it deploys.

**Comment by kevinold** [comment]
I think so as it documents the Dashboard Analytics as they are now, but @amirrustam will need to make the final call.

**Comment by amirrustam** [comment]
The public beta of the Analytics feature is not released yet. We'll merge this in once it is. This PR is preparation for the initial beta release.

**Comment by kevinold** [comment]
@amirrustam Added instructions - https://github.com/cypress-io/cypress-documentation/pull/2249/commits/7c35863c23798f5e23eeaa2d3ae9a6834441ea53 Ready for merge

**Pull request merged**
