### PR TITLE
feat: add copy button to code blocks

### PR DESCRIPTION
**Pull request by admah**
copy-button

This PR adds a copy button to code blocks within API and Guides pages. The button will not appear within API blocks that demonstrate incorrect usage.

### CODE REVIEW

**Comment by jennifer-shehane** [comment]
Had to comment that I love this. 😍 Extra props for not showing it on broken examples.

The copy button is a little weird when the scrollbar is present. I know y'all were discussing the scrolling with long code in another PR.

**Comment by admah** [comment]
@jennifer-shehane thank you! I agree that it's not great UX when there's a scrollbar. I'll take another pass at it. 

Maybe I can just position the button top-right absolute in that box and see what it looks like.

**Comment by admah** [comment]
https://user-images.githubusercontent.com/2184114/123290010-8b4b7480-d4d6-11eb-82d8-10772706600c.mov

Updated the way the code element flexes when there is a copy button. Blocks without copy buttons remain as-is - full-width in the parent container.

**Comment by jennifer-shehane** [comment]
I don't think this is ideal, to reduce the width of all code blocks available. It's also not obviously that there may be more content hidden with the content hidding 85% of the width in. Maybe the copy button could sit outside of the code content box? Like, static positioned in the black margin somewhere? Just my observations. Up to y'all.

**Comment by admah** [comment]
@jennifer-shehane thanks so much for the feedback! Here is an iteration where the button sits on top and does not limit the width of the code block below:

**Comment by jennifer-shehane** [comment]
Yah, still a little weird with the long examples, but this is an improvement overall I think. 👍  Can iterate on more improvements for the scrolling experience if needed.

**Comment by admah** [comment]
Closing in favor of #4015

**Pull request closed without merging**
