### PR TITLE
Updated courses list with three new courses

### PR DESCRIPTION
**Pull request by wlsf82**
I posted these new courses on Twitter and @bahmutov suggested adding them here.

### CODE REVIEW

**Comment by wlsf82** [comment]
@bahmutov, do you mind reviewing this PR, please?

**Comment by wlsf82** [comment]
@bahmutov, I saw that this PR was merged into `cypress-io:develop`. Out of curiosity, how does this process work, and when can I expect to see my changes live?

**Comment by bahmutov** [comment]
usually we create a pull request from `develop` to `master` (which goes live) after we merge a few PRs. We have tried automating it, but I now see that it has been failing https://github.com/cypress-io/cypress-documentation/issues/2356 

I will try to sort it out to get your links live as soon as possible

**Comment by bahmutov** [comment]
I have merged `develop` into `master` with your change, in about 20 minutes it should be live after deploy

**Pull request merged**
