### PR TITLE
Remove outdated workshops

### LINKED ISSUE #5864: Outdated workshop entries with legacy Cypress versions
### Subject

[Examples > Workshops](https://docs.cypress.io/examples/workshop) 

#### Issue

The [Examples > Workshops](https://docs.cypress.io/examples/workshop) page contains 2 outdated workshops:

##### End-to-end Testing with Cypress.io

[Examples > Workshops > End-to-end Testing with Cypress.io](https://docs.cypress.io/examples/workshop#End-to-end-Testing-with-Cypressio)

- The Cypress version used is the legacy Cypress `7.6.0` version
- The associated repository https://github.com/cypress-io/testing-workshop-cypress is archived.

##### ReactJSDay 2019 Testing Course

[Examples > Workshops > ReactJSDay 2019 Testing Course](https://docs.cypress.io/examples/workshop#ReactJSDay-2019-Testing-Course)

- The Cypress version used is the legacy Cypress `5.6.0` version
- The associated repository https://github.com/NoriSte/reactjsday-2019-testing-course was last updated 4 years ago.

#### Suggestion

Consider removing both the above workshops as they use legacy Cypress version [7.6.0](https://docs.cypress.io/guides/references/changelog#7-6-0), released on June 23, 2021 and legacy Cypress version [5.6.0](https://docs.cypress.io/guides/references/changelog#5-6-0), released on November 9, 2020.

### PR DESCRIPTION
**Pull request by MikeMcC399**
- closes #5864

## Issue

The [Examples > Workshops](https://docs.cypress.io/examples/workshop) page contains 2 outdated workshops:

- [Examples > Workshops > End-to-end Testing with Cypress.io](https://docs.cypress.io/examples/workshop#End-to-end-Testing-with-Cypressio)
- [Examples > Workshops > ReactJSDay 2019 Testing Course](https://docs.cypress.io/examples/workshop#ReactJSDay-2019-Testing-Course)

which are both based on legacy versions of Cypress.

## Changes

- Remove the above outdated workshops
- Add a link to Cypress Events https://www.cypress.io/events

### CODE REVIEW

**Comment by MikeMcC399** [comment]
Preview

https://github.com/MikeMcC399/cypress-documentation/blob/remove/old-workshops/docs/examples/workshop.mdx

**Review by jennifer-shehane — CHANGES_REQUESTED** [review]
Oh, I see. There's nothing here. 😅 We can probably just remove this entire page from the docs. Let me know if you need any assistance.

**Comment by MikeMcC399** [comment]
@jennifer-shehane 

> We can probably just remove this entire page from the docs. 

Done

**Review by jennifer-shehane — APPROVED** [review]
This seems fine. People directed to the workshop URL or the old workshop URL will see a 404 page, but the nav is present there and I think should be fine for someone to find where they want to go. We don't have an exact match for where to redirect them to. 

Screenshot 2024-07-09 at 10 54 38 AM

**Pull request merged**
