### PR TITLE
Added Buildkite

### PR DESCRIPTION
**Pull request by jakebresnehan**
It is in the CI error output but not the docs :)

### CODE REVIEW

**Review by jennifer-shehane — CHANGES_REQUESTED** [review]
This is meant to reflect the buildID number pulled from buildkite. I'm actually not sure which value we use exactly. They have `BUILDKITE_JOB_ID`, `BUILDKITE_BUILD_ID`, and `BUILDKITE_BUILD_NUMBER` which all sound very similar.

**Review by amirrustam — CHANGES_REQUESTED** [review]
Thanks for pointing this out.

Cypress itself is [aware of the proper buildkite env vars](https://github.com/cypress-io/cypress/search?q=BUILDKITE_BUILD_ID). But after digging through our backend codebase, we actually do not have native recognition of all the buildkite environment details for parallelization.

This is why buildkite users have been using `--ci-build-id=BUILDKITE_BUILD_ID` to use parallelization and grouping.

I'll have our Services team make the proper changes to give Buildkite the same first-class experience we provide for other popular CI providers.

**Comment by amirrustam** [comment]
@traviscy once our Services have been updated to better support Buildkite we can merge this.

**Comment by estrada9166** [comment]
@jakebresnehan thank you for opening this PR - can you resolve the conflicts, please?

**Pull request closed without merging**
