### PR TITLE
docs: add argos to plugin list

### PR DESCRIPTION
**Pull request by jsfez**
This PR adds [Argos](https://www.argos-ci.com) to visual testing plugins list.

Here is the plugin GitHub's repo: [@argos-ci/cypress plugin](https://docs.argos-ci.com/cypress).

- [x] The repository has integration tests with cypress with a real-world like example
- [x] The test with this plugin is tested on a real-world like scenario
- [x] The test runs inside our CI pipeline
- [x] The plugin is compatible with the latest major version of Cypress

### CODE REVIEW

**Comment by jsfez** [comment]
Hi @lmiller1990,

I have a Github check that require an approval from a Cypress team member to turn green. I see that you have approved this kind of PR in the past. So, could you please review this PR?

ps. If you are not the good person to ask, could you tell me who is it?

Thank you,

**Comment by jsfez** [comment]
Hello @elylucas, 
It seems like I have ping the wrong person to get PR approval. Are you the right person to contact to have PR review? If yes, could you please review this PR?
Thank you,

**Review by lmiller1990 — APPROVED** [review]

**Comment by lmiller1990** [comment]
Ely is definitely the right person, let me ping him, too.

**Review by BlueWinds — APPROVED** [review]

**Comment by jsfez** [comment]
Hi, thanks a lot!

**Pull request merged**
