### PR TITLE
Remove outdated non-working "Test a React Todo App" tutorial

### PR DESCRIPTION
**Pull request by MikeMcC399**
- Closes https://github.com/cypress-io/cypress-documentation/issues/5623

This PR removes the outdated Cypress tutorial from [Examples > Tutorial Videos > Test a React Todo App](https://docs.cypress.io/examples/tutorials#Test-a-React-Todo-App) which was based on the legacy Cypress version [cypress@3.5.0](https://docs.cypress.io/guides/references/changelog#3-5-0) released on Oct 23, 2019.

There was no plan to update this tutorial to current Cypress versions and the old version no longer works correctly under currently supported operating systems and Node.js versions.

### Repositories

The associated repos referred to in the tutorial should be archived:

- [x] [cypress-io/cypress-tutorial-build-todo](https://github.com/cypress-io/cypress-tutorial-build-todo/)
- [ ] [cypress-io/cypress-tutorial-build-todo-starter](https://github.com/cypress-io/cypress-tutorial-build-todo-starter)

### Videos

Possibly the related video recordings in [Cypress.io on vimeo](https://vimeo.com/user72267166) should also be removed or archived.

1. https://vimeo.com/240554515
2. https://vimeo.com/240554808
3. https://vimeo.com/241063147
4. https://vimeo.com/241773142
5. https://vimeo.com/242954792
6. https://vimeo.com/242961930
7. https://vimeo.com/244696145
8. https://vimeo.com/245387683
9. https://vimeo.com/245388948

### CODE REVIEW

**Comment by MikeMcC399** [comment]
- According to the proposal in https://github.com/cypress-io/cypress-documentation/issues/5623#issuecomment-1922227337 from @jennifer-shehane, the tutorial [Examples > Tutorial Videos > Test a React Todo App](https://docs.cypress.io/examples/tutorials#Test-a-React-Todo-App) should be archived, since there are no plans to update the tutorial recordings.

A preview of the edited page, with the "Test a React Todo App" removed, is available for review on https://deploy-preview-5624--benevolent-cat-040f48.netlify.app/examples/tutorials

**Review by jennifer-shehane — APPROVED** [review]

**Comment by jennifer-shehane** [comment]
Should probably just remove this page altogether. It's kind of sad now.

**Comment by jennifer-shehane** [comment]
@MikeMcC399 Thanks again!

**Comment by MikeMcC399** [comment]
@jennifer-shehane 

> Should probably just remove this page altogether. It's kind of sad now.

It would be good to review the remaining content.

I guess that the YouTube link is fine.
Should there be a link to Vimeo?
The link to https://learn.cypress.io/ is in the footer, so doesn't need to be repeated.

**Pull request merged**
