### PR TITLE
write code coverage guide

### LINKED ISSUE #1705: Add code coverage guide to tooling
We need a good code coverage story for people who want it from their e2e tests
- https://github.com/cypress-io/cypress/issues/346

Probably will make a separate repo or cypress-example-recipe (it is that simple) that shows instrumentation.

For comparison: TodoMVC unit tests from Redux repo

Screen Shot 2019-05-21 at 2 21 47 PM

while our e2e spec plus a couple of unit tests (including edge case tested using cypress-react-unit-test) hit 100%

Screen Shot 2019-05-21 at 2 58 05 PM

Screen Shot 2019-05-21 at 5 07 40 PM

### PR DESCRIPTION
**Pull request by bahmutov**
- closes #1705

### CODE REVIEW

**Comment by jennifer-shehane** [comment]
I will give this a look tomorrow. Got caught up in some performance testing today.

**Comment by bahmutov** [comment]
Gotcha

**Comment by bahmutov** [comment]
@jennifer-shehane appreciate your feedback and understand what you mean, I will add an introduction to make it super clear why we are jumping into Istanbul and instrumentation

**Comment by bahmutov** [comment]
wrote introduction section that should gently explain code coverage, also added links to a blog post that is pretty good explaining the same thing in detail

**Comment by jennifer-shehane** [comment]
oh, I just realized I forgot to push my previous changes. Will be merging this in. sorry.

**Pull request merged**
