### PR TITLE
Translation for Chinese

### PR DESCRIPTION
**Pull request by icelemon1314**
Translation for Chinese. Thanks to all the people involved in the translation.

### Translations updated

Changes made to documentation were also copied over to other languages (**copying English text is ok**).

- [ ] Japanese docs in [`/source/ja`](/source/ja).
- [ ] Chinese docs in [`/source/zh-cn`](/source/zh-cn).
- [ ] Not applicable (this is not a change to an `en` doc content).

### CODE REVIEW

**Comment by icelemon1314** [comment]
In the circleci check, I got the error, but I think this may not be a problem, I think we should modify the circleci program.

/root/cypress-documentation/source/zh-cn/guides/references/assertions.md
   53:10  ✓ error  Incorrect usage of the term: “regexp”, use “RegExp” instead  terminology
  135:9   ✓ error  Incorrect usage of the term: “html”, use “HTML” instead      terminology

/root/cypress-documentation/source/zh-cn/guides/tooling/reporters.md
  164:49  ✓ error  Incorrect usage of the term: “Cypress'”, use “Cypress's” instead  terminology

**Comment by jennifer-shehane** [comment]
@icelemon1314 We have text linting to ensure English terminology has the correct and consistent spelling and capitalization. These checks are correct. `regexp` should be changed to `RegExp`, `html` should be change to `HTML` and `Cypress'` should be changed to `Cypress's`

**Comment by icelemon1314** [comment]
image

So there will be one more s on the page.

**Comment by jennifer-shehane** [comment]
No, this should be 'Cypress', there may be a linting error where it's reading `Cypress'` within the url as being an apostrophe instead of escaping the url value. I can take a look at it.

**Pull request merged**
