### PR TITLE
Add cypress-plugin-stripe-elements to plugins list

### PR DESCRIPTION
**Pull request by dbalatero**
I created a new plugin to assist with filling Stripe Elements inputs, as this seemed to be a large-ish problem people were having!

### CODE REVIEW

**Comment by jennifer-shehane** [comment]
Thanks for submitting the plugin! Please check to see if it fulfills these requirements:

- [ ] 🚀 Works with the latest major version of Cypress
- [ ] 🛠 Plugin purpose is clearly documented (in a README or docs website)
- [ ] 📝 Well-written documentation - A great example ([link](https://github.com/Fredx87/cypress-keycloak-commands#cypress-keycloak-commands))
- [ ] 🔬 Tested using Cypress - tests using Cypress can act as both example usage _and_ test coverage
- [ ] 👷‍♀️ CI pipeline that's passing (CircleCI and [Github Actions](https://github.com/cypress-io/cypress-tutorial-build-todo/blob/master/.github/workflows) are both free for Open Source)

If you have reason to believe your plugin does not need to meet certain requirements, please feel free to provide justification.

**Comment by dbalatero** [comment]
> Works with the latest major version of Cypress

Yes, the test suite runs against 6.x.

> Plugin purpose is clearly documented (in a README or docs website)
> Well-written documentation - A great example

Yes, see [README.md](https://github.com/dbalatero/cypress-plugin-stripe-elements#readme) of the repo.

> Tested using Cypress - tests using Cypress can act as both example usage and test coverage

Yes

> CI pipeline that's passing (CircleCI and Github Actions are both free for Open Source)

I beat my head against the wall trying to get CircleCI to work, but every single time I do `cypress run` on CI, it hangs uncompleted for 10 minutes then the process is killed.

Here are multiple Cypress issues about similar problems:

* https://github.com/cypress-io/cypress/issues/6695
* https://github.com/cypress-io/cypress/issues/8206
* https://github.com/cypress-io/cypress/issues/5645
* https://github.com/cypress-io/cypress/issues/7464
* https://github.com/cypress-io/cypress/issues/5139
* https://github.com/cypress-io/cypress/issues/7026
* https://github.com/cypress-io/cypress/issues/7174

Something really weird is going on in the world of Cypress + CI + (docker?) but after 6 hours of trying I gave up. It runs perfect on my Mac laptop locally, so I just have the `prepublish` task include `yarn test` as a step I take before releasing a version.

Is this ok?

**Comment by dbalatero** [comment]
Oh, this is the branch I'm trying to get CircleCI working in:
https://github.com/dbalatero/cypress-plugin-stripe-elements/pull/1

Thanks!

**Comment by dbalatero** [comment]
@jennifer-shehane Ok, I actually got Github Actions setup and it only took like 20-30mins and a couple of pushes. This should satisfy your final requirement (CI!)

**Comment by dbalatero** [comment]
Thanks!

**Pull request merged**
