### PR TITLE
Fixed dark mode switch Button: Update DarkModeSwitch

### PR DESCRIPTION
**Pull request by Suhas2299**
Issue : 
1. User sets dark theme and closes tab,
2. Again user visits cypress doc
3. Now the theme remains dark but button is stucked in light theme 

Fix:
The default value is now set from localstorage.

Resolution:
 Darkmode switch button now remembers the user set value.

### CODE REVIEW

**Comment by MikeMcC399** [comment]
@Suhas2299 

Which browser were you having problems with (Browser / browser version / operating system)? 

For me with Google Chrome 127.0.6533.100 on Windows 11 and Google Chrome 127.0.6533.9 on Ubuntu `22.04.4` LTS the dark / light mode setting is persistent already.

**Comment by Suhas2299** [comment]
Hi @MikeMcC399 ,

 I am using google chrome on windows 11 Version 127.0.6533.100 (Official Build) (64-bit) i am getting issue on browser PFB : 

image

Steps Followed : Enabled Dark mode >> Close Tab/Browser >> Revisited the document >> Found the doc is in dark mode but the DarkModeSwitch Button is stuck in light mode

**Comment by MikeMcC399** [comment]
@Suhas2299 

Thanks for explaining and apologies for my misunderstanding!

I misread the issue and see now the same problem you pointed out. The light / dark mode button should be aligned to the light/dark state of the site.

**Comment by Suhas2299** [comment]
@MikeMcC399  No worries at all, glad we're on the same page now! 
Thanks.

**Review by elevatebart — APPROVED** [review]
TYTY

**Comment by MikeMcC399** [comment]
@Suhas2299 / @elevatebart 

Could you check if this PR has solved this issue in production?

I'm still seeing the switch in light mode when the site is displayed in dark mode.

image

You can get the same effect if you press F5 when the site is in dark mode. The switch changes to light mode whilst the site stays in dark mode.

**Comment by Suhas2299** [comment]
Hi @MikeMcC399 , 
The Issue works right in local but the issue still persists in the production, @MikeMcC399 / @elevatebart Can you please share your expertise what factors might me affecting the changes in Production?

**Comment by MikeMcC399** [comment]
@Suhas2299 

Thanks for confirming you are also seeing the issue unresolved in production! Unfortunately I don't have the expertise to debug further or to suggest a fix.

**Pull request merged**
