### PR TITLE
Update to make code valid

### PR DESCRIPTION
**Pull request by lmiller1990**
`del` module no longer has a default export, you need `del.deleteAsync`.

### CODE REVIEW

**Review by emilyrohrbough — APPROVED** [review]

**Comment by lmiller1990** [comment]
CI is failing but I can't see why - I do not seem to have access to Netlify to view the logs. I will make a tech request, but in the meantime, does anyone else who has access know what's the problem?

**Comment by adamalston** [comment]
Are there any updates on this PR beyond what's listed above?

**Comment by MikeMcC399** [comment]
The PR is outdated and would need to be rebased.

**Comment by warrensplayer** [comment]
@lmiller1990 It looks like this PR has been superseded by the changes here: https://github.com/cypress-io/cypress-documentation/pull/5198

Can this PR just be closed?

**Pull request closed without merging**
