### PR TITLE
Update all text references of Dashboard to Cloud

### PR DESCRIPTION
**Pull request by mattvCypress**
**This PR should not be merged until we are ready to roll out the final rebrand on 11/16/22.**

### CODE REVIEW

**Comment by mattvCypress** [comment]
Remaining items to do:

- [ ] Update on.cypress.io/dashboard link to redirect to Cloud
- [ ] Create on.cypress.io/cloud link and link to cloud.cypress.io
- [ ] Update **assets/img/dashboard** directory and all references
- [ ] Update **content/faq/dashboard-faq.md** file name and all references
- [ ] Update **content/guides/dashboard** directory and all references
- [ ] Redirects for old **dashboard** links that are now **cloud**

**Comment by mattvCypress** [comment]
@debrisapron I rebased this morning and pulled in your latest changes from Master. I had one conflict with the Cloud Introduction page and cleared that up (your new header banner). Our plan is to merge this PR on 11/16

**Review by debrisapron — APPROVED** [review]

**Review by brian-mann — CHANGES_REQUESTED** [review]
I was on a PR review for an unrelated issue and realized that if we're renaming all of the existing `/dashboard/*` URL's to cloud, that we need to add redirects for every renamed file inside of `redirects.js` so users bookmarking old links get forwarded to the new ones.

https://github.com/cypress-io/cypress-documentation/pull/4719/files#diff-0c2a003b2ed5170c245944b00d0738dcfd9ee35f449ffb10252b159c5a457af1

https://github.com/cypress-io/cypress-documentation/blob/mvollmer-change-dashboard-to-cloud/redirects.js

**Comment by mattvCypress** [comment]
> I was on a PR review for an unrelated issue and realized that if we're renaming all of the existing `/dashboard/*` URL's to cloud, that we need to add redirects for every renamed file inside of `redirects.js` so users bookmarking old links get forwarded to the new ones.
> 
> I see that you did one indicated below... but I believe every existing `/dashboard/*` URL needs to be redirected
> 
> image
> 
> The redirects file in the PR is here: https://github.com/cypress-io/cypress-documentation/pull/4719/files#diff-0c2a003b2ed5170c245944b00d0738dcfd9ee35f449ffb10252b159c5a457af1
> 
> And here is the file directly: https://github.com/cypress-io/cypress-documentation/blob/mvollmer-change-dashboard-to-cloud/redirects.js
> 
> You may be able to use like a glob or wildcard pattern to dynamically set the redirects, but worst case you'll just add a manual entry for each one.

@brian-mann I recall this coming up in a conversation months ago and I walked away with the understanding that only the netlify.toml file needed to be updated -- something about the redirects.js file you mentioned not actually doing anything.

https://github.com/cypress-io/cypress-documentation/blob/mvollmer-change-dashboard-to-cloud/netlify.toml

**Comment by brian-mann** [comment]
Oh I could be *totally* wrong about the redirects... I just saw that edited and assumed that's where the functionality is. I didn't look at the `netlify.toml` so if that's been updated to incorporate this then disregard my review

**Pull request merged**
