### PR TITLE
DX-37-update-screenshots

### PR DESCRIPTION
**Pull request by jaffrepaul**
https://cypress-io.atlassian.net/browse/UDX-37

The following pages have updated screenshots & gifs:
<google-sheets-html-origin>

**Overview** |   |  
-- | -- | --
Why Cypress? | https://cypress-documentation-git-udx-37-update-screenshots-cypress-io.vercel.app/guides/overview/why-cypress#What-you-ll-learn |  
**Getting Started** |   |  
Writing Your First Test (e2e) | https://cypress-documentation-git-udx-37-update-screenshots-cypress-io.vercel.app/guides/getting-started/writing-your-first-end-to-end-test |  
Testing You App | https://cypress-documentation-git-udx-37-update-screenshots-cypress-io.vercel.app/guides/getting-started/testing-your-app#What-you-ll-learn |  
Writing Your First Test (ct) | https://cypress-documentation-git-udx-37-update-screenshots-cypress-io.vercel.app/guides/getting-started/writing-your-first-component-test |  
**Core Concepts** |   |  
Introduction to Cypress | https://cypress-documentation-git-udx-37-update-screenshots-cypress-io.vercel.app/guides/core-concepts/introduction-to-cypress#What-you-ll-learn |  
Writing and organizing tests | https://cypress-documentation-git-udx-37-update-screenshots-cypress-io.vercel.app/guides/core-concepts/writing-and-organizing-tests |  
Retry-ability | https://cypress-documentation-git-udx-37-update-screenshots-cypress-io.vercel.app/guides/core-concepts/retry-ability |  
Interacting with elements | https://cypress-documentation-git-udx-37-update-screenshots-cypress-io.vercel.app/guides/core-concepts/interacting-with-elements |  
Variables & Aliases | https://cypress-documentation-git-udx-37-update-screenshots-cypress-io.vercel.app/guides/core-concepts/variables-and-aliases |  
Cypress App | https://cypress-documentation-git-udx-37-update-screenshots-cypress-io.vercel.app/guides/core-concepts/cypress-app |  Selector Playground throws an exception in v10 command log. Waiting on bug fix to capture these gifs
**Guides** |   |  
Debugging | https://cypress-documentation-git-udx-37-update-screenshots-cypress-io.vercel.app/guides/guides/debugging |  
Network Requests | https://cypress-documentation-git-udx-37-update-screenshots-cypress-io.vercel.app/guides/guides/network-requests | need revised content & command log screenshots
Test Retries | https://cypress-documentation-git-udx-37-update-screenshots-cypress-io.vercel.app/guides/guides/test-retries |  
Launching Browsers | https://cypress-documentation-git-udx-37-update-screenshots-cypress-io.vercel.app/guides/guides/launching-browsers |
Cross Browser Testing | https://cypress-documentation-git-udx-37-update-screenshots-cypress-io.vercel.app/guides/guides/cross-browser-testing |  
References |   |  
Configuration | https://cypress-documentation-git-udx-37-update-screenshots-cypress-io.vercel.app/guides/references/configuration |

### CODE REVIEW

**Comment by jordanpowell88** [comment]
This is super nitpicky but I feel like [https://cypress-documentation-git-udx-37-update-screenshots-cypress-io.vercel.app/_nuxt/img/spec-file-list.123c70f.png](this image) feels abnormally tall.

**Review by debrisapron — CHANGES_REQUESTED** [review]
There's an embedded YouTube video (by Gleb) at the end of the Retry-ability page which shows the old UI. Should this be removed and replaced with an animated gif showing the same functionality? Here's the video in question: https://youtu.be/AlltFcsIFvc

**Review by debrisapron — APPROVED** [review]

**Comment by jaffrepaul** [comment]
> This is super nitpicky but I feel like [this image](https://cypress-documentation-git-udx-37-update-screenshots-cypress-io.vercel.app/_nuxt/img/spec-file-list.123c70f.png) feels abnormally tall.

It its. This is a funny example because we're walking through adding one spec and then showing the UI. I tried to include the full UI since it's new and good to get users comfy. So there's a ton of dead space. I'll shoot for a smaller version of this if not it can just be cropped if it's still weird.

**Comment by jordanpowell88** [comment]
spec-file-list 123c70f
Can you use this?

**Comment by robertguss** [comment]
@jaffrepaul in the test retries guide, this screenshot is confusing to me:
Screen Shot 2022-04-01 at 1 45 13 PM

It seems to be the exact same as the one just above it and I am not sure if it is even necessary?

**Comment by robertguss** [comment]
@jaffrepaul in the launching browsers guide there is this screenshot of the old runner UI:
Screen Shot 2022-04-01 at 1 50 15 PM

**Comment by robertguss** [comment]
@jaffrepaul this screenshot is really hard to read/see in the launching browsers guide:
Screen Shot 2022-04-01 at 1 51 35 PM

**Comment by jaffrepaul** [comment]
> @jaffrepaul in the test retries guide, this screenshot is confusing to me: Screen Shot 2022-04-01 at 1 45 13 PM
> 
> It seems to be the exact same as the one just above it and I am not sure if it is even necessary?

Devil's in the details on these. The content is talking about what happens during retries. And the screenshots show the same things but in an attempt retry state. But agree, it's not the most compelling content to display. I'll leave this one for now since it's just recreating what we currently have and we can tweak content/images accordingly in a new ticket. 

Screen Shot 2022-04-01 at 2 04 39 PM

**Pull request merged**
