### PR TITLE
added baseRegex to guides nav link to fix active highlighting bug

### PR DESCRIPTION
**Pull request by robertguss**
- fixe bug where the guides link in the nav was always active and selected.

### CODE REVIEW

**Review by jaffrepaul — CHANGES_REQUESTED** [review]
What does this property end up doing? Wasn't sure how this is working. 

The only thing now is that the "guides" nav element never has a selected state, even when it's the only thing selected.

**Comment by robertguss** [comment]
@jaffrepaul it doesn't have a selected state when you are on the "home page" or why why cypress page. If you click on any of the docs under the guides you will see it get highlighted. I hope that makes sense.

**Comment by jaffrepaul** [comment]
> @jaffrepaul it doesn't have a selected state when you are on the "home page" or why why cypress page. If you click on any of the docs under the guides you will see it get highlighted. I hope that makes sense.

Got it. I hadn't clicked around enough. It feels like a bit of weird UX that it doesn't highlight. Like it's the complete opposite that it used to be "selected" too much and now, not enough 😆 I'm curious to know if this is a bi product of our weird hierarchy or an actual technical issue.

**Comment by robertguss** [comment]
@jaffrepaul I am honestly not sure what the issue is, it is very strange. It seems to work just fine as far as I can tell, the only time it does not activate is when you are on the root route ie "/" which is the why cypress page.

**Pull request merged**
