### PR TITLE
add plugin `cypress-temp-mail` : Temporary email provider for cypress testing

### PR DESCRIPTION
**Pull request by madhusaran**
Lightweight NPM package with quick setup that offers temporary test email accounts to facilitate end-to-end testing

### CODE REVIEW

**Comment by MikeMcC399** [comment]
@madhusaran 

In the related repo https://github.com/madhusaran/cypress-temp-mail the workflow 
https://github.com/madhusaran/cypress-temp-mail/blob/main/.github/workflows/node.js.yml tests on Node.js versions 
`14.x` & `16.x` which have reached end-of-life, and it misses out testing on the active Node.js version 
`20.x` and `22.x`.

It would be advisable to update your test matrix to cover the versions which Cypress supports (currently `18.x`, `20.x` and above). See also 
https://docs.cypress.io/guides/getting-started/installing-cypress#Nodejs

At this stage I would not consider Node.js `21.x` as it goes into end-of-life in just a few days on June 1, 2024.

```yml
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
```

**Comment by madhusaran** [comment]
@MikeMcC399 Thanks for your inputs. As advised, updated the node version to '22.x' in the work flow

**Comment by MikeMcC399** [comment]
@madhusaran 

> As advised, updated the node version to '22.x' and '20.x' in the work flow
> 
> https://github.com/madhusaran/cypress-temp-mail/blob/main/.github/workflows/node.js.yml

You have deleted `18.x` which remains a supported version until April 2025. It would make sense to put that back in again.

**Comment by madhusaran** [comment]
@MikeMcC399  Added `18.x` too
image
https://github.com/madhusaran/cypress-temp-mail/blob/main/.github/workflows/node.js.yml

**Comment by madhusaran** [comment]
@MikeMcC399 Updated as advised.
image

**Comment by madhusaran** [comment]
Hey @MikeMcC399,  Are we good to merge the PR?

**Comment by MikeMcC399** [comment]
Hello @madhusaran 

You'll need to wait for the Cypress.io team to pick up your PR and review it. It was a long weekend in USA so I expect they still have a lot in their to-do queue. I'm an external contributor and I can't personally merge PRs.

**Comment by madhusaran** [comment]
@jennifer-shehane Are we good to close the PR? Please advise

**Review by jennifer-shehane — APPROVED** [review]

**Pull request merged**
