### PR TITLE
Update user & remove outdated image

### PR DESCRIPTION
**Pull request by jaffrepaul**
The Free, Team, and Business plans each allow for 50 users.

### CODE REVIEW

**Comment by MikeMcC399** [comment]
So now the FAQ section 

https://docs.cypress.io/faq/questions/cloud-faq#Does-the-replay-reflect-the-real-time-it-took-for-the-test-to-run (50 users)
image

is not consistent with the page it links to
https://www.cypress.io/pricing (3 users)

image

**Comment by jaffrepaul** [comment]
Thanks for the hawk eye, @MikeMcC399. This was a coordinated effort across different teams, so cypress.io was also updated in sequence to reflect the changes.

**Comment by MikeMcC399** [comment]
@jaffrepaul 

Thanks for cross-checking. I was viewing before the website had caught up. It looks fine now.

Will there be an announcement e.g. in https://www.cypress.io/blog and/or the [Discord announcement channgel](https://discord.com/channels/755913899261296641/958013993425960971)?

**Comment by jennifer-shehane** [comment]
@MikeMcC399 We'll be sending emails to affected accounts and also notifying within the Cloud. Not sure about a blog post or broader at this point. These changes are all live though, so feel free to communicate it so.

**Comment by MikeMcC399** [comment]
https://www.cypress.io/blog/2023/11/07/exciting-news-cypress-cloud-plan-user-limits-increased-to-50 has announced this.

**Pull request merged**
