### PR TITLE
docs: Write section on how to run cypress without an X11 server

### PR DESCRIPTION
**Pull request by mrmeku**
As requested here: https://github.com/cypress-io/cypress/pull/16537#issuecomment-876591922

### CODE REVIEW

**Comment by cowboy** [comment]
@mrmeku this looks great. One request: can you also link to this from the [Launching Browsers "Electron Browser"](https://docs.cypress.io/guides/guides/launching-browsers#Electron-Browser) section in the docs?

**Comment by jennifer-shehane** [comment]
@mrmeku Could you please sign our CLA? It's required for each repo separately. Thanks!

**Comment by jennifer-shehane** [comment]
Updating the base branch to 8.0

**Review by jennifer-shehane — APPROVED** [review]

**Comment by jennifer-shehane** [comment]
Thanks @mrmeku again for all the work!

**Comment by mrmeku** [comment]
@jennifer-shehane Thanks for being a great repo maintainer. I just wanted to mention that this has been one of the least painful open source contributions I've done in years. Thank the whole team for me if you could

**Pull request merged**
