### PR TITLE
docs: Update okta-authentication.md

### PR DESCRIPTION
**Pull request by vanhumbeecka**
Replace the incorrect `scope` to `scopes`. Otherwise, the default scopes of `['openid', 'email']` will be used without the given `profile` one. (lost couple of hours because of this documentation bug.)

### CODE REVIEW

**Comment by jaffrepaul** [comment]
@AtofStryker I know you worked a bit on the auth strategies. Are you able to confirm this change? 

@vanhumbeecka can you please resolve any conflicts here since this PR older? 

🙏

**Comment by AtofStryker** [comment]
@jaffrepaul based on the [docs](https://github.com/okta/okta-auth-js#scopes) it looks like `scopes` is correct and this is a bug

**Comment by AtofStryker** [comment]
@jaffrepaul @vanhumbeecka I also fixed the conflict. Once the tests pass this should be good to merge in

**Review by AtofStryker — APPROVED** [review]

**Comment by jaffrepaul** [comment]
Thanks @AtofStryker!

**Pull request merged**
