### PR TITLE
Moved Custom Reporters section to bottom the page

### PR DESCRIPTION
**Pull request by urig-develeap**
To improve usability.

### Translations updated

Changes made to documentation were also copied over to other languages (copying English text is fine).

- [ ] Japanese docs in [`/source/ja`](/source/ja).
- [ ] Chinese docs in [`/source/zh-cn`](/source/zh-cn).
- [ ] Not applicable (this is not a change to an `en` doc content).

### CODE REVIEW

**Comment by bahmutov** [comment]
makes sense to me to put default built-in reporters at the top and custom reporters at the bottom. We should also link the "reporters" section of the testing workshop there https://github.com/cypress-io/testing-workshop-cypress#reporters

**Comment by urig-develeap** [comment]
@jennifer-shehane looks like the problem is with this little bit that I added:

```
{% testing workshop for Cypress https://github.com/cypress-io/testing-workshop-cypress %}
```

Where does this `{% %}` type of templating come from? It'll be easier for me to fix if I can browse their documentation. Tx!

**Comment by jennifer-shehane** [comment]
@urig-develeap 	The tags are described here: https://github.com/cypress-io/cypress-documentation/blob/develop/TAGS.md

**Comment by urig-develeap** [comment]
@jennifer-shehane Thanks. Fixed, pushed and passes tests :+1:

**Pull request merged**
