### PR TITLE
add allure plugin

### PR DESCRIPTION
**Pull request by Shelex**
add link for allure reporter plugin
https://github.com/Shelex/cypress-allure-plugin

### CODE REVIEW

**Review by gabrielbussolo — APPROVED** [review]
Nice work @Shelex !
Thanks! :+1:

**Comment by jennifer-shehane** [comment]
@gabrielferreirapro We have some more thorough review that we conduct on plugins before publishing. You can see the checks here: https://github.com/cypress-io/cypress-documentation/pull/2530#pullrequestreview-383137611

**Comment by Shelex** [comment]
> #2530 (review)

**Comment by gabrielferreirapro** [comment]
> @gabrielferreirapro We have some more thorough review that we conduct on plugins before publishing. You can see the checks here: [#2530 (review)](https://github.com/cypress-io/cypress-documentation/pull/2530#pullrequestreview-383137611)

Thank you! I will use it as a guide from now on. :bowtie:

**Comment by bencodezen** [comment]
👋 Hello and thank you for your contribution!

We are currently reviewing your plugin. As a heads up, we accept plugins that meet the following criteria:

- [ ] 🚀 Works with the latest major version of Cypress (we can validate this once you have tests in place)
- [x] 🛠Plugin purpose is clearly documented (in a README or docs website)
- [x] 📄Well-written documentation - A great example ([link](https://github.com/Fredx87/cypress-keycloak-commands#cypress-keycloak-commands))
- [ ] 🔬Tests - Has tests that validate the primary function of the reporter
- [ ] 👷‍♀️ CI pipeline that's passing (CircleCI and [Github Actions](https://github.com/cypress-io/cypress-tutorial-build-todo/blob/master/.github/workflows) are both free for Open Source)

We are currently blocked from reviewing your plugin since it requires tests before we can proceed. Let us know if you have any questions!

**Review by bencodezen — CHANGES_REQUESTED** [review]
Needs tests in plugin repo before review can continue

**Comment by Shelex** [comment]
> Needs tests in plugin repo before review can continue

 - added tests
 - used Cypress 4.5.0
 - added badge for github-action workflow status.

**Comment by bencodezen** [comment]
Thanks for the updates @Shelex!

**Review by bencodezen — APPROVED** [review]

**Comment by amirrustam** [comment]
@Shelex thank you for contributing this plugin 🙏

**Comment by Shelex** [comment]
@amirrustam Thanks!
Btw, based on https://github.com/cypress-io/cypress-documentation/pull/2747#issuecomment-627474840 should I replace cypress logo for [Cypress Helper](https://marketplace.visualstudio.com/items?itemName=Shelex.vscode-cy-helper&ssr=false#overview) vscode extension?

**Comment by amirrustam** [comment]
That would be preferable, and a good long-term move in case our logo changes.

**Pull request merged**
