### PR TITLE
docs: update clashing types with jest answer

### LINKED ISSUE #4559: Document adding `./cypress.config.ts` to `tsconfig.exclude` to avoid conflicts with Jest
### Subject

Guides - component testing troubleshooting

### Description

We should update the [Cypress Types Conflict with Jest](https://docs.cypress.io/guides/component-testing/component-test-troubleshooting#Cypress-Types-Conflict-with-Jest
) section of the docs to reflect the [solution outlined here](https://github.com/cypress-io/cypress/issues/22059#issuecomment-1148921141) by @ZachJW34 to the issue reported in https://github.com/cypress-io/cypress/issues/22059.

It's also been suggested in that issue to surface this in the migration guide, which I think is not a bad idea.

I'm creating this issue in the docs so that we can close the issue in the main repo and add the information to our main docs.

### PR DESCRIPTION
**Pull request by bchen1029**
closes #4559 
see: https://github.com/cypress-io/cypress/issues/22059 for discussion

### CODE REVIEW

**Comment by bchen1029** [comment]
Hoping this is a major priority! thx~

**Review by maria-kravtsova — APPROVED** [review]
Yes, please merge this!

**Comment by garmeeh** [comment]
Hey @bchen1029 I also needed to add `cypress` to my exclude for it to work. 

Not sure if it was something on my end but just in case the docs should reflect it.

```json
{
  "exclude": ["cypress.config.ts", "cypress", "node_modules"]
}
```

We are using `react-scripts@5.0.1`

**Comment by bchen1029** [comment]
> Hey @bchen1029 I also needed to add `cypress` to my exclude for it to work.
> 
> Not sure if it was something on my end but just in case the docs should reflect it.
> 
> ```json
> {
>   "exclude": ["cypress.config.ts", "cypress", "node_modules"]
> }
> ```
> 
> We are using `react-scripts@5.0.1`

and also need to add `node_modules ` to exclude right ?

**Comment by garmeeh** [comment]
@bchen1029 sorry, I missed the notification on your reply. I wasn’t 100% sure on if node_modules should be there but seen some examples with it so added it. I don’t think it is doing any harm being there anyway.

**Comment by bchen1029** [comment]
> Yes, please merge this!

@maria-kravtsova could you help merge this PR if you're free? It might be helpful for cypress users, really appreciate:)

**Comment by marktnoonan** [comment]
@elylucas I'm not sure how the Vercel authorization step works?

**Review by jennifer-shehane — APPROVED** [review]

**Comment by jennifer-shehane** [comment]
I created a new PR to track this since this one is so out of date

**Pull request closed without merging**
