### PR TITLE
Update plugins.yml to include cypress-lighthouse

### PR DESCRIPTION
**Pull request by gkemp94**
Hi all, just published a cypress plugin that allows you to run lighthouse audits from within cypress and assert based on the returned scores. Adding to the plugins.yml

### CODE REVIEW

**Review by jennifer-shehane — DISMISSED** [review]
Hey @gkemp94, we do a quick smoke tests of plugins before adding them to the docs and I wasn't able to run your plugin. I opened an issue here: https://github.com/gkemp94/cypress-lighthouse/issues/3

**Comment by gkemp94** [comment]
Hi @jennifer-shehane , Thanks for the review! I did see this a little during development but couldn't replicate it consistently. I will continue to investigate and fix, I'll also add the documentation. 

Thanks, 
George

**Comment by bahmutov** [comment]
I love it, look at https://www.npmjs.com/package/cypress-audit

**Comment by jennifer-shehane** [comment]
Hey @gkemp94, were you able to look at the issue initially opened around the plugin?

**Review by JessicaSachs — CHANGES_REQUESTED** [review]
Thank you so much for your contribution. A lighthouse integration plugin is a great idea. I re-reviewed your plugin and had no issues running it on OSX Catalina.

We're trying to improve the process to add plugins to our plugin page, so we're now accepting plugins that meet the following criteria:

- [x] 🚀 Works with the latest major version of Cypress
- [x] 🛠 Plugin purpose is clearly documented (in a README or docs website)
- [x] 📄 Well-written documentation with code snippets - A great example ([link](https://github.com/Fredx87/cypress-keycloak-commands#cypress-keycloak-commands))
- [ ] 🧪 Tested using Cypress - tests using Cypress can act as both example usage _and_ test coverage
- [ ] 👷‍♀️ CI pipeline that's passing (CircleCI and [Github Actions](https://github.com/cypress-io/cypress-tutorial-build-todo/blob/master/.github/workflows) are both free for Open Source)

If you could put together some cypress tests to serve as documentation and CI that runs those tests, that would be greatly appreciated. I'm happy to help you out and submit a pull request to your plugin if you have trouble adding CI or Cypress tests.

**Comment by amirrustam** [comment]
@gkemp94 thanks for the contribution. Will you be able to make the requested changes?

**Comment by gkemp94** [comment]
Hi @amirrustam, 
Yes I'll make these changes this weekend. 

Thanks,
George

**Comment by amirrustam** [comment]
Hi @gkemp94, once you get the chance to make those changes feel free to reopen this PR and request my review :)

**Pull request closed without merging**
