### PR TITLE
Adding cypress-audit to the plugin list

### PR DESCRIPTION
**Pull request by mfrachet**
Adding the cypress-audit plugin to the plugin list

- Repo: https://github.com/mfrachet/cypress-audit
- Description: Run Lighthouse audit directly in your E2E test suites

### CODE REVIEW

**Comment by jennifer-shehane** [comment]
Thanks for the contribution! Could you please sign our CLA?

**Comment by mfrachet** [comment]
The page says that I did 🤔:

Screenshot 2020-02-18 at 09 10 01

**Comment by jennifer-shehane** [comment]
@mfrachet K, yah it's showing as signed now 👍

**Review by bahmutov — APPROVED** [review]
I love it, I tried it in https://github.com/cypress-io/cypress-example-todomvc/tree/add-lighthouse-audit and opened a couple of little usability issues, but overall I think this is a great idea

**Pull request merged**
