### PR TITLE
docs: add cypress-plugin-dotenv

### PR DESCRIPTION
**Pull request by MohamadKh75**
❤️

### CODE REVIEW

**Comment by MohamadKh75** [comment]
Should I remove [cypress-dotenv](https://github.com/morficus/cypress-dotenv) too?
It's not working with Cypress +10

**Comment by MikeMcC399** [comment]
@MohamadKh75 

You might like to cross-check against the plugins template. I couldn't see any CI pipeline on https://github.com/MohamadKh75/cypress-plugin-dotenv.

Before submitting your plugin, please check to see if it fulfills these requirements:

- [ ] 🚀 Works with the latest major version of Cypress
- [ ] 🛠 Plugin purpose is clearly documented (in a README or docs website)
- [ ] 📝 Well-written documentation - A great example ([link](https://github.com/Fredx87/cypress-keycloak-commands#cypress-keycloak-commands))
- [ ] 🔬 Tested using Cypress - tests using Cypress can act as both example usage _and_ test coverage
- [ ] 👷‍♀️ CI pipeline that's passing (CircleCI and [Github Actions](https://github.com/cypress-io/cypress-tutorial-build-todo/blob/main/.github/workflows) are both free for Open Source)

If you have reason to believe your plugin does not need to meet certain requirements, please feel free to provide justification below:

**Comment by MohamadKh75** [comment]
Hey @MikeMcC399 

I have noted in README that there is an example. (cypress folder)
I check, and it's working with the latest version of Cypress.
It's a very simple plugin, and README contains enough docs and information.

**Comment by jaffrepaul** [comment]
@MohamadKh75 there are a couple of things that will help us get this added. As mentioned above, please use the plugin acceptance criteria. Seeing a passing CI pipeline is a great indicator of success and helps us with triaging contributions.

> Before submitting your plugin, please check to see if it fulfills these requirements:
> 
> - [ ] 🚀 Works with the latest major version of Cypress
> - [ ] 🛠 Plugin purpose is clearly documented (in a README or docs website)
> - [ ] 📝 Well-written documentation - A great example ([link](https://github.com/Fredx87/cypress-keycloak-commands#cypress-keycloak-commands))
> - [ ] 🔬 Tested using Cypress - tests using Cypress can act as both example usage _and_ test coverage
> - [ ] 👷‍♀️ CI pipeline that's passing (CircleCI and [Github Actions](https://github.com/cypress-io/cypress-tutorial-build-todo/blob/main/.github/workflows) are both free for Open Source)
> 
> If you have reason to believe your plugin does not need to meet certain requirements, please feel free to provide justification below:

Also, for bonus points (and to answer your question), there is another [cypress-dotenv](https://github.com/morficus/cypress-dotenv) plugin listed on the docs page. This was supporting pre v10 Cypress. It'd be a big help as part of this PR if you can place that near the bottom of the page in the "Legacy" section. 

Thanks! We look forward to your contribution. 

💪 💪

**Comment by MohamadKh75** [comment]
I used GitHub actions to test and it's passing.
Also, I moved the other plugin to the legacy section.

@MikeMcC399 @jaffrepaul

**Comment by jaffrepaul** [comment]
Awesome @MohamadKh75 thanks for the extra legwork. We just released v13 today. Can we get your tests updated to run on the _latest_ Cypress version? Then we should be good to merge 💪

**Review by jaffrepaul — CHANGES_REQUESTED** [review]
Just need to get a passing test with Cypress v13, which was released today.

**Comment by MohamadKh75** [comment]
Done @jaffrepaul

**Review by jaffrepaul — APPROVED** [review]

**Pull request merged**
