### PR TITLE
Add Issue Template

### PR DESCRIPTION
**Pull request by duyphaphach**
I want to add an Issue Template so it is easier for everyone to raise an issue
This PR refer to issue #1360
This is my first ever contribution so please tell me if anything is not ok, I will update right away ^^

### CODE REVIEW

**Comment by jennifer-shehane** [comment]
Having an Issue Template is not a bad idea. We would need significant changes to this issue template though, since it looks like it would fit a project that is not documentation.

**Comment by duyphaphach** [comment]
@jennifer-shehane 
So sorry, I did not notice that this was a documentation
I updated the Issue template so that it fits better with your repo
Could you please take a look at it

**Comment by jennifer-shehane** [comment]
Thanks for signing the CLA, unfortunately the author of the commits does not match the email address on your GitHub account. Our CLA bot gets confused when they don't match. Here are some solutions to fixing when commits are linked to the wrong user: https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/

**Comment by duyphaphach** [comment]
Yes, I updated my emails settings to complete CLA verification.
I'm very grateful for your kind feedback.

**Pull request merged**
