### PR TITLE
Add note about Electron run as node being experimental

### PR DESCRIPTION
**Pull request by jennifer-shehane**
As noted in the original PR for this feature, we’re not fully testing it so should note it as experimental. https://github.com/cypress-io/cypress/pull/16537#pullrequestreview-701384541

Inspired by https://github.com/cypress-io/cypress/issues/17412

### CODE REVIEW

**Comment by cowboy** [comment]
@jennifer-shehane would it be possible to break this PR into 2 commits: the first commit with just the file reformats (by saving any to-be-changed files without any edits) and a second commit with just the copy changes? Until we can merge #4028, this approach will help code reviews.

**Comment by jennifer-shehane** [comment]
@cowboy Looks like that PR was closed. I'm not a fan of the line break linting in general. This  seems like a user specific IDE setting if people want to view files this way. It's really awkward when editing  as I have to jump  across lines with my cursor to edit a single sentence.

**Comment by cowboy** [comment]
> @cowboy Looks like that PR was closed. I'm not a fan of the line break linting in general. This seems like a user specific IDE setting if people want to view files this way. It's really awkward when editing as I have to jump across lines with my cursor to edit a single sentence.

@robertguss is going to be opening a new one!

**Comment by cowboy** [comment]
@jennifer-shehane now that the docs reformatting PR has been merged, if you can rebase this onto master, it should resolve the review issue I was having. Thanks!

**Comment by cowboy** [comment]
@jennifer-shehane I just resolved the conflicts and force-pushed, I'll review once the preview build is done

**Review by cowboy — APPROVED** [review]
LGTM

**Pull request merged**
