### PR TITLE
Add .circleci/config.yml

### PR DESCRIPTION
**Pull request by romoaldodoliz**

### CODE REVIEW

**Comment by MikeMcC399** [comment]
This looks like an experiment which should not be used on the production version of this repository.

**Comment by romoaldodoliz** [comment]
I do understand I was trying to show the wrong syntax that is on your official page code used for example

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by MikeMcC399** [comment]
@romoaldodoliz 

You have submitted 3 PRs to this repository. See https://github.com/cypress-io/cypress-documentation/pulls/romoaldodoliz

Please review which ones you want to keep and close the other ones.

**Comment by nagash77** [comment]
@romoaldodoliz if you are intending to open PRs into the this repo please fill out the description with more information.  What is the purpose of the PR, what are you adding/subtracting/altering, etc.  I am going to close this PR until those fields are filled out.

**Pull request closed without merging**
