### PR TITLE
Update courses page with new course

### PR DESCRIPTION
**Pull request by wlsf82**
Also, update other of my courses with https URL

### CODE REVIEW

**Comment by wlsf82** [comment]
Hi @bahmutov, can you review this PR, please?

**Comment by bahmutov** [comment]
nice

**Comment by wlsf82** [comment]
@bahmutov, if possible, let me know when the change is production, please? :wink:

**Comment by bahmutov** [comment]
there was a flaky test that failed the develop, now it has passed and is building auto-PR into master to be deployed https://github.com/cypress-io/cypress-documentation/pull/2492

**Pull request merged**
