### PR TITLE
7.0 Release (next docs)

### PR DESCRIPTION
**Pull request by jennifer-shehane**
For https://github.com/cypress-io/cypress/pull/14690

Close previous docs PR: https://github.com/cypress-io/cypress-documentation/pull/3518

*Targeted release date: Mar 29, 2021*

- [x] Changelog (missing item for Component Testing in Changelog)
- [x] Component testing migration guide https://github.com/cypress-io/cypress-documentation/pull/3759
- [x] Migration guide for 7.0
- [x] Remove Cypress.moment() page https://github.com/cypress-io/cypress-documentation/pull/3519
- [x] Update minimum Node.js version supported https://github.com/cypress-io/cypress-documentation/pull/3614
- [x] Note for route2 removal https://github.com/cypress-io/cypress-documentation/pull/3517
- [x] document redirectionLimit https://github.com/cypress-io/cypress-documentation/pull/3573
- [x] cy.submit form validation https://github.com/cypress-io/cypress-documentation/pull/3608
- [x] Uncaught error handling https://github.com/cypress-io/cypress-documentation/pull/3615
- [x] cy.intercept changes https://github.com/cypress-io/cypress-documentation/pull/3715
- [x] Add log:false to cy.tick() https://github.com/cypress-io/cypress/pull/15586 https://github.com/cypress-io/cypress-documentation/pull/3613/commits/3825bfe87160b5bbab99a48e35a39f389918f2ef
- [x] `component` versus `e2e` config https://github.com/cypress-io/cypress-documentation/pull/3693
- [x] Component Testing doc https://github.com/cypress-io/cypress-documentation/pull/3610
---

- [ ] Remove Cypress.moment() on link from services (non-blocking)

### CODE REVIEW

**Comment by amirrustam** [comment]
Percy snapshotting is getting improved (DX-46), for today's release feel free to approve the changes in Percy. Ping me if you don't have Percy permissions. cc @jennifer-shehane

**Comment by jennifer-shehane** [comment]
@amirrustam These percy snapshots seem a bit overboard to have to approve for every content change. Some percy changes are showing up because the photos previously didn't load also.

**Comment by jennifer-shehane** [comment]
Realistically, I'm unlikely to take the time to look through 30+ pages in percy to approve them all and will just approve it to move on. 😬 Especially since each page takes a while to load in percy cause the snapshots are large.

**Comment by amirrustam** [comment]
@jennifer-shehane I'm with you! That's kinda what I was referring to with https://github.com/cypress-io/cypress-documentation/pull/3613#issuecomment-809532564. We can block out content sections and narrow down the snapshotting to UI bits.

**Comment by lmiller1990** [comment]
I notice the only task outstanding is changelog for Component Testing. We have a section in the changelog under breaking changes:

image

The migrate guide linked to is [also extensive - lines 141 - 491](https://github.com/cypress-io/cypress-documentation/pull/3613/files#diff-50ef08355b192e64726bbf1dd0e050ca1f1612d1472de477168d37baa529bf5cR141-R491)

image

Anything else that needs to be included @jennifer-shehane?

**Review by chrisbreiding — APPROVED** [review]

**Pull request merged**
