### PR TITLE
Remove duplicated sentence

### PR DESCRIPTION
**Pull request by Tbaut**
Removes a sentence that is repeated twice in the doc (see the line below).

ps: Congrats, your documentation is really good, it's such a pleasure to read and follow :tada:

### CODE REVIEW

**Review by bahmutov — CHANGES_REQUESTED** [review]
I don't think this line is a duplicate, I think this is an intentional description of "learn more" link that is present in some error messages

**Comment by Tbaut** [comment]
This is actually what the line below says, with almost the exact same words "some error messages contain a Learn More..."

**Comment by bahmutov** [comment]
I see what you mean, good catch

**Review by bahmutov — APPROVED** [review]
good catch

**Pull request merged**
