### PR TITLE
Changing name of 'Free' plan to 'Starter' plan

### PR DESCRIPTION
**Pull request by danjohansenconsulting**
This PR will coincide with changes that will be published to our cypress.io website. There will be two PRs, but this is the PR that is urgent to time-up with our website PR. The benefits and features remain the same, but the name is changing from 'free' to 'starter'. It also provides necessary information that new orgs created in Cypress Cloud will automatically be enrolled in a no-obligation free trial for 2 weeks.  More details and walkthrough of the free trial period will take place in a separate PR.

### CODE REVIEW

**Comment by danjohansenconsulting** [comment]
@elevatebart @MikeMcC399 - can one of you glance at the PR and provide any critical feedback?  Looking to launch this EOD.  It is the smaller of two PRs so that we can ensure a seamless launch and time it up with a website PR.

**Comment by MikeMcC399** [comment]
@danjohansenconsulting 

The screenshots still refer to "Free"

**Comment by danjohansenconsulting** [comment]
@MikeMcC399 - I'm cycling back through to see "where" those are.  The only one I had found was guides/cloud/account-management/billing-and-usage and that is one that could be changed, but isn't even the free plan that exists today.  do you have an example?

**Comment by MikeMcC399** [comment]
image

image

**Comment by danjohansenconsulting** [comment]
yeah, the first one I wasn't worried about because it's the wrong plan and needs to be changed anyway.  The open source plan is more obvious.  I'll update that image and see if I can snag a view of the first one while I'm at it.

**Review by jennifer-shehane — CHANGES_REQUESTED** [review]
Some areas that could be updated:
- https://github.com/cypress-io/cypress-documentation/blob/develop/docs/faq/questions/cloud-faq.mdx#-what-happens-once-i-reach-the-test-results-limit
- https://github.com/cypress-io/cypress-documentation/blob/develop/docs/faq/questions/general-questions-faq.mdx#-is-cypress-free-and-open-source (maybe mention free trial here)
- I would probably mention a free trial plan for every 'paid' feature:
	- https://github.com/cypress-io/cypress-documentation/blob/develop/docs/guides/cloud/flaky-test-management.mdx#flake-detection
	- https://github.com/cypress-io/cypress-documentation/blob/develop/docs/guides/cloud/flaky-test-management.mdx#flaky-test-analytics
	- https://github.com/cypress-io/cypress-documentation/blob/develop/docs/guides/cloud/flaky-test-management.mdx#flake-alerting
	- https://github.com/cypress-io/cypress-documentation/blob/develop/docs/guides/cloud/account-management/enterprise-sso.mdx (not sure if this is included in trial)
- https://github.com/cypress-io/cypress-documentation/blob/develop/docs/guides/cloud/analytics/enterprise-reporting.mdx (not sure if this is included in trial)
- there's a bunch more pages you should check that mention features are only available with a specific 'plan'.

**Comment by danjohansenconsulting** [comment]
Addressed the two screen caps, and the missed 'free' reference on the FAQ page.  Wording for the premium cloud features available only in business or enterprise plans will be evaluated as a future scope, but keeping this on-par with the prior content and focusing only on the new free trial / starter plan.

@jennifer-shehane @MikeMcC399 ready for one more glance, please.

**Review by MikeMcC399 — APPROVED** [review]
You requested review and it looks good as far as I can judge!

**Review by jennifer-shehane — APPROVED** [review]

**Pull request merged**
