### PR TITLE
WIP: Redesign Navigation

### LINKED ISSUE #990: Update sidebar navigation design to accommodate growing menus.
- [x] expand/collapse each sidebar section (with animation)
- [x] have 'expand all' and 'collapse all' at top of sidebar
- [x] highlight heading of section of page we are on
~- [ ] when clicking on a new page, keep previous sections that were open - open~
- [x] put links to entire API on main API page to facility `cmd+f` searching
- [x] update fonts + general design to be fresher
- [x] have click event bubble to `li` when clicking on `strong` section header
- [x] fix issue where collapse animation is not working
- [x] fix responsive views

### PR DESCRIPTION
**Pull request by jennifer-shehane**
- close #990 
- not ready for review

### CODE REVIEW

**Comment by jennifer-shehane** [comment]
Errors in build
```
Error: File to import not found or unreadable: ../../mixins.
Error: File to import not found or unreadable: ../../mixins.
Error: File to import not found or unreadable: ../../mixins.
ERROR Asset render failed: fonts/vendor/roboto/css/roboto/sass/roboto-fontface-black-italic.css
Error: File to import not found or unreadable: ../../mixins.
    at options.error (/root/cypress-documentation/node_modules/node-sass/lib/index.js:291:26)
ERROR Asset render failed: fonts/vendor/roboto/css/roboto/sass/roboto-fontface-black.css
Error: File to import not found or unreadable: ../../mixins.
    at options.error (/root/cypress-documentation/node_modules/node-sass/lib/index.js:291:26)
ERROR Asset render failed: fonts/vendor/roboto/css/roboto/sass/roboto-fontface-bold-italic.css
Error: File to import not found or unreadable: ../../mixins.
    at options.error (/root/cypress-documentation/node_modules/node-sass/lib/index.js:291:26)
```

**Comment by jennifer-shehane** [comment]
Error in tests
```
Uncaught TypeError: (intermediate value)(...) is not a function
```

**Comment by brian-mann** [comment]
@jennifer-shehane i fixed the merge conflicts from the latest `develop` for you

**Comment by brian-mann** [comment]
Can we auto expand the left nav when `categories.length <= 2` such as the `Examples` page?

screen shot 2018-10-01 at 6 24 44 pm

**Comment by brian-mann** [comment]
Table of contents at the top font size is too small / out of proportion to the others.

screen shot 2018-10-01 at 6 24 18 pm

**Comment by brian-mann** [comment]
Line height is too large.

screen shot 2018-10-01 at 7 10 25 pm

Compare that to React's docs...

screen shot 2018-10-01 at 7 10 34 pm

screen shot 2018-10-01 at 7 10 22 pm

**Comment by brian-mann** [comment]
Font size of code blocks is too large.

screen shot 2018-10-01 at 6 20 59 pm

**Comment by brian-mann** [comment]
Font size in helper notes is too large.

screen shot 2018-10-01 at 6 19 39 pm

**Comment by brian-mann** [comment]
This is broken in the main docs as well but can we do something about this to clean it up? Maybe style the scrollbar?

screen shot 2018-10-01 at 6 18 19 pm

**Comment by brian-mann** [comment]
Footer next / back has scrollbar

screen shot 2018-10-01 at 6 18 10 pm

**Comment by brian-mann** [comment]
On hover... the section category is activating its `:active` or `:hover` styles even when hovered on children, which acts strange.

screen shot 2018-10-01 at 6 16 39 pm

**Comment by brian-mann** [comment]
The border of the left nav is barely visible and initially its hard to see that it's its own thing. Can we add a light gray / blue background color to help distinguish it away from the actual content?

React does this by shading their nav in gray - which helps separate it from the real content and makes it easier on your eyes to focus on the content.

screen shot 2018-10-01 at 7 18 34 pm

Compared to ours...

screen shot 2018-10-01 at 7 18 56 pm

**Comment by brian-mann** [comment]
Table of contents on the right is too small compared to rest of font.

screen shot 2018-10-01 at 7 19 27 pm

**Comment by brian-mann** [comment]
Remove left nav scrollbar.

No scroll bar but still scrollable.

screen shot 2018-10-01 at 7 30 21 pm

screen shot 2018-10-01 at 7 30 26 pm

screen shot 2018-10-01 at 7 30 35 pm

**Comment by lilaconlee** [comment]
Looks like the light grey and the green don't have great contrast from looking at the lighthouse accessibility audit, might be worth tweaking a bit.

**Comment by brian-mann** [comment]
Another thought - can we make `Expand All / Collapse All` show up **only** when you hover over those sections? It would be less distracting until you actually want to interact with those buttons.

...just an idea™️

**Comment by brian-mann** [comment]
The info boxes background blue is barely noticeable, and the `--record` text color is hard to distinguish from the darker background blue.

screen shot 2018-10-02 at 5 05 42 pm

**Comment by brian-mann** [comment]
Is the lighter background color behind the text intended?

It's not there when you have codeblocks.

screen shot 2018-10-02 at 4 57 57 pm

**Comment by brian-mann** [comment]
It looks like you actually **changed** the `info` notes to become `success` notes, and this doesn’t make sense because it's changing the actual semantics of what these things mean...

I strongly prefer reverting to the original intentions of the `note` blocks - so `info` is info and `success` is success and not changing their relationships.

screen shot 2018-10-02 at 4 53 29 pm

screen shot 2018-10-02 at 4 53 31 pm

**Comment by brian-mann** [comment]
I don't see any line-height changes in the last round of changes - so I still feel like there's too much whitespace on bullets and paragraphs.

I also still feel like the docs are too large overall - as if I'm accidentally zoomed into chrome.

screen shot 2018-10-02 at 5 10 07 pm

**Comment by jennifer-shehane** [comment]
screen shot 2018-10-03 at 3 56 30 pm

**Pull request merged**
