### PR TITLE
Provide proper `--args` for any place utilizing rawRender

### LINKED ISSUE #2196: --arg not writing `--` when in inline code blocks
## I'm submitting a...

```
[x] Bug report
[ ] Content update
[ ] Process update (build, deployment, ... )
```

## Type of bug / changes

When typing `--arg` in the docs, it formats it as `-arg`

Screenshot 2019-10-25 11 52 42

It appears this hacky fix is no longer working: https://github.com/cypress-io/cypress-documentation/pull/935

### PR DESCRIPTION
**Pull request by andrew-codes**
- `changelog.js`
- `note.js` now renders with rawRender

Blocks of `<code>--arg</code>` are converted to `<code>-arg</code>`. This does not occur when code is within a code block; i.e. 
```
`--arg`
```
The desire is to maintain the double `--` in output. A fix was put in for `note.js` in PR #935. This fix was moved to `rawRender.js` so that any renderer using this will pick up this fix; including `changelog.js`. Also, update `note.js` to leverage `rawRender`.

Close #2196

### CODE REVIEW

**Comment by andrew-codes** [comment]
Closing for now to explore upgrading `marked` dep

**Comment by andrew-codes** [comment]
Reopening this PR: the alternative approach of upgrading seems like a decent size undertaking.

**Comment by andrew-codes** [comment]
Note: this will not fix cases where more than a fenced code block in in the `%{ url }` helper like below:

```
 {% url "`--config-file` argument" command-line#cypress-run-config-file-lt-config-file-gt %}
```

**Comment by jennifer-shehane** [comment]
This does fix cases where the `--` is in a fenced code block in a url, but not the first characters. The below renders correctly:

```
{% url "`cypress run --browser chrome`" command-line#cypress-run-browser-lt-browser-name-or-path-gt %}
```

**Comment by jennifer-shehane** [comment]
Actually, I'm starting to think that this issue was always isolated to text within code blocks within urls where the beginning text was `--`. Is there any evidence this has fixed any cases in the changelog that existed before?

**Comment by andrew-codes** [comment]
It does appear to fix some as shown in the below image; just not all.

image

**Comment by oak-wildwood** [comment]
Looks like this might have broken the notes tag rendering.

**Pull request merged**
