### PR TITLE
117 Add supported Platforms

### PR DESCRIPTION
**Pull request by arnazmursidp**
#117 
[x] Add Cypress' supported OS version readme

### CODE REVIEW

**Comment by bahmutov** [comment]
@arnazmursidp 

Thank you for the submission, we appreciate it. Could you add to the windows line a recommendation to watch https://github.com/cypress-io/cypress/issues/74 to know the windows support status?

Also, the CLA seems to not find your email from the commit?

**Comment by arnazmursidp** [comment]
oh okay i'll fix it, sorry

**Comment by jennifer-shehane** [comment]
Hi @arnazmursidp, were you able to [add the email address used for this commit to your account.](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user)?

**Comment by arnazmursidp** [comment]
Hi @jennifer-shehane i couldn't find the page and what the message were, cause there are no exclamation mark as they said in the documentation

**Comment by RandallKent** [comment]
Hey @arnazmursidp! 

I cloned [your repo](https://github.com/arnazmursidp/cypress-documentation) and ran `git show cd03853296f87605f5ee12a5c7a58cdab96adda7` which shows the email address that needs to be [added to your GitHub account](https://help.github.com/articles/adding-an-email-address-to-your-github-account/) to be `arnazmursidp.arnazmursid@gmail.com`. 

Let me know once it has been added and I'll remove it from this comment to keep the spambots away 😄

**Comment by arnazmursidp** [comment]
@RandallKent oh thank you for the confirmation, but I already set thet email to be my primary email, i don't really know what is wrong...

**Comment by bahmutov** [comment]
I see CLA signed by `arnazmursidp` not sure why check has not passed. Will approve and merge, thank you @arnazmursidp !

**Comment by arnazmursidp** [comment]
@bahmutov thank you so much, thanks for letting me in!

**Pull request merged**
