### PR TITLE
docs: document mode argument to plugins

### PR DESCRIPTION
**Pull request by lmiller1990**
This PR introduced some additional config options to support Component Testing: https://github.com/cypress-io/cypress/pull/15526

I have updated the documentation to reflect these changes.

### CODE REVIEW

**Review by jennifer-shehane — DISMISSED** [review]
I opened a pull request for some suggested updates. https://github.com/cypress-io/cypress-documentation/pull/3696

**Comment by lmiller1990** [comment]
Thanks @jennifer-shehane. I think we should leave this open a moment, looks like there is a little more feedback around the API and implementation. `mode` may become a property on the second arg, `config`, to plugins. Let's wait and see.

I will ping you again once it's 100% finalized and the PR is merged.

**Comment by lmiller1990** [comment]
@jennifer-shehane @amirrustam @matthamil The relevant feature was finally merged into develop: https://github.com/cypress-io/cypress/pull/15526. Please review and let me know if I need to make any changes.

**Review by amirrustam — APPROVED** [review]

**Comment by amirrustam** [comment]
This is part of v7 release, so not merging yet.

**Review by jennifer-shehane — APPROVED** [review]

**Pull request merged**
