### PR TITLE
Add docs for Firefox support

### PR DESCRIPTION
**Pull request by chrisbreiding**
Updates existing browser-related docs to include Firefox and adds new docs for browser-related methods added to `Cypress`.

Depends on https://github.com/cypress-io/cypress/pull/1359 being released.

### CODE REVIEW

**Comment by jennifer-shehane** [comment]
Make sure to update cypress-on to reflect new documents https://github.com/cypress-io/cypress-on/issues/59

**Comment by vutukuriswathi** [comment]
I did not find any updated documentation for firefox.Can you please help me in finding how to run on firefox.

I tried the below command

./node_modules/.bin/cypress run --browser firefox
Warning: Cypress can only record videos when using the built in 'electron' browser.

You have set the browser to: 'firefox'

A video will not be recorded when using this browser.
  (Tests Starting)


  (All Done)

Browser: 'firefox' was not found on your system.

Available browsers found are: chrome, electron

I got the above error but firefox browser is installed on my system

**Comment by chrisbreiding** [comment]
@vutukuriswathi Firefox support has not been released yet. Subscribe to [this issue](https://github.com/cypress-io/cypress/issues/1096) and you'll be notified when we release it.

**Comment by jennifer-shehane** [comment]
Closing in favor of https://github.com/cypress-io/cypress-documentation/pull/2225

**Pull request closed without merging**
