### PR TITLE
Add assertion after select

### PR DESCRIPTION
**Pull request by ootsuka**
Add assertion after select to address issue #216

### CODE REVIEW

**Comment by jennifer-shehane** [comment]
Since the commit author does not match the email address on your GitHub account, would it be possible for you to add the email used during commit to your GitHub account? Out CLA gets confused when they don't match. https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user

**Comment by ootsuka** [comment]
I think when I first committed I had a generic email address which I can never get to, I tried to change that but I think I screwed the pull request.:(

**Comment by ootsuka** [comment]
Hi Jennifer I think I am gonna close this pull request and open another one. I have now set my git with correct email address and username. Sorry for causing confusion and trouble.

**Comment by jennifer-shehane** [comment]
@ootsuka No problem, this is more common than you think. :P

**Pull request closed without merging**
