### PR TITLE
docs: Add amplify v6 to e2e testing strategy for cognito auth (#5609)

### LINKED ISSUE #5609: Add instructions for amplify v6 to e2e testing strategy with AWS Cognito Authentication
### Subject

guides

### Description

I've submitted a [pull request](https://github.com/cypress-io/cypress-documentation/pull/5610) to add instructions for using AWS Amplify v6 to the e2e testing strategy using AWS Cognito Authentication.  I've built and tested the change locally, using &lt;Tabs&gt; to preserve the v5 instructions as default, but when crafting a git commit message I noticed that every recent commit message seems to reference an issue number, so I came here to file an issue to obtain that number to then provide in my git commit message.

edit: oops.  Looks like those commit messages referenced pull request numbers, not issue numbers. Sorry for my confusion; happy to fix things as needed if needed.

### PR DESCRIPTION
**Pull request by timheilman**
I got amplify v6 working based on the instructions here for amplify v5, and wanted to contribute back to the community a similar working implementation. Corresponding issue: https://github.com/cypress-io/cypress-documentation/issues/5609

The real-world-app is updated to this approach in https://github.com/cypress-io/cypress-realworld-app/pull/1513

closes #5609

### CODE REVIEW

**Comment by timheilman** [comment]
looks like prettier was having trouble understanding the &lt;Tabs&gt; addition. I tried `npm upgrade prettier` but still had the issue. I noticed &lt;!-- prettier-ignore-start&gt; and &lt;!-- prettier-ignore-end --&gt; used elsewhere in the repo, and so used the same approach.

**Comment by timheilman** [comment]
@jennifer-shehane Thank you for the title rename! I'm cutting my teeth here.

This change would've been helpful to me and encouraged my use of cypress if it had been present.  Any chance of a review?

**Comment by timheilman** [comment]
I'm grateful the v5 amplify docs are there to give the guidance they do.  Thank you for this great project!

**Comment by timheilman** [comment]
I guess I closed this PR by mistake.

**Review by AtofStryker — APPROVED** [review]
Thanks for the contribution @timheilman ! Would you be able to update the examples in [cypress-realworld-app](https://github.com/cypress-io/cypress-realworld-app)? I created a [branch](https://github.com/cypress-io/cypress-realworld-app/compare/chore/update_aws_amplify) that might work as a starting point

**Comment by timheilman** [comment]
Well, I gave it a shot, but in so doing I realized I've been confused regarding what this e2e testing strategy guide in cypress-documentation is intended to accomplish. This PR certainly does not achieve an upgrade to amplify v6 for all of that intent.

What I managed to get working, and what is represented in this PR, is only programmatic authentication _against a Cognito User Pool directly_, using the `Authenticator` component from `@aws-amplify/react-ui` _without_ any `socialProviders` attribute. In the project I managed to get this working, I was not using the Cognito Hosted UI. I was not using a Cognito identity pool.  No redirects occur at my login screen, as it is not an Oauth/OIDC login. I also did not try to use `cy.origin()` to provide the login with a cypress session.  If I had tried to do so, I would have discovered that the `cy.origin()` call would have been irrelevant, _because_ this was not an oauth login.

Nonetheless, the guide that this e2e testing strategy provided was still useful to programmatically obtain the JWTs _as though_ the `Authenticator` component from `@aws-amplify/ui-react` _without_ a `socialProviders` attribute had been used.

Over in `cypress-realworld-app`, it seems to me that none of the four (cognito, auth0, okta, and google) oauth provider tests are working currently. What makes it seem that way is that during the upgrade there from `create-react-app` to `vite`, some env vars that had been `REACT_APP_...` were changed to `VITE_APP_...` when their intended new names were just `VITE_...`. The oauth tests using `VITE_APP_...` rather than `VITE_...` do not run, so I don't think anyone has run these tests successfully since the vite upgrade.

Furthermore, it seems that same upgrade from create-react-app to vite also included an upgrade of `@aws-amplify/ui-react` from major version 1 to major version 5. As part of that upgrade, it looks to me like the `Authenticator` component was introduced, but _without_ the value `'amazon'` in the `socialProviders` attribute.  Since no `socialProviders` are specified, the component will never initiate an Oauth flow, no redirects will occur, and `cy.origin()` will be irrelevant. So, I suspect that the `cognito` oauth test in particular has never run successfully since the upgrade regardless of the `VITE_APP...` vs `VITE_` issue.

Given that this PR does not provide relevant instructions to use cognito _identity pools_ as an oauth identity provider nor to use the Cognito hosted login UI, at v6, which is what the original guide intended at v5, it probably should not be merged.

**Comment by timheilman** [comment]
put back in draft to see if I can get oauth working for cognito in the realworld app

**Comment by timheilman** [comment]
okay, https://github.com/cypress-io/cypress-realworld-app/pull/1513 is up to implement not only the programmatic login but also the cy.origin() login, using oauth with a cognito user pool hosted login UI.  I'll update this PR soon w/the lessons learned there copied into the docs here.

**Review by AtofStryker — APPROVED** [review]
> The oauth tests using VITE_APP_... rather than VITE_... do not run, so I don't think anyone has run these tests successfully since the vite upgrade.

That sounds correct. The update was a large lift and a lot of these auth tests do not run in CI, so what I think happened was a best guess was determined on what would happen and it was not verified. Thank you for updating the variables for all the examples as who knows who has been running into this for some time. It sounds like some TLC was needed. 

I gave the update code a similar run with my set up locally outside the context of RWA and feel confident in the changes. Thank you for updating these guides and the RWA examples. Hopefully the task didn't consume too much time!

**Pull request merged**
