### PR TITLE
docs: add cypress-codegen plugin

### PR DESCRIPTION
**Pull request by danadajian**
Adds [cypress-codegen](https://github.com/ExpediaGroup/cypress-codegen) to the plugins page! This plugin conforms to the ["Adding Plugins" documentation](https://github.com/cypress-io/cypress-documentation/blob/master/CONTRIBUTING.md#adding-plugins). This plugin currently works with e2e and component testing on Cypress 10!

### CODE REVIEW

**Comment by danadajian** [comment]
@elylucas I noticed you recently reviewed a new plugin submission in #4320 and was wondering if you could take a look at this if you have a chance? 😃

**Comment by danadajian** [comment]
@lmiller1990 Would you mind taking a look at this? 😄

**Review by lmiller1990 — APPROVED** [review]
Sounds good to me. This is neat, we define all ours manually, maybe we should consider using this. 

I do not have merge permissions here (weird). Maybe @elylucas or @admah can merge this up?

**Comment by danadajian** [comment]
@admah Would you mind reviewing this?

**Review by elylucas — APPROVED** [review]
lgtm! Thanks!

**Pull request merged**
